name: dot_noi_buon_ngay13_14
description: Ứng dụng đốt nỗi buồn có cảm xúc, chuyển giọng nói và giao diện tự đổi.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  audioplayers: ^5.2.1
  shared_preferences: ^2.2.2
  lottie: ^2.6.0
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  speech_to_text: ^7.0.0
  flutter_launcher_icons: ^0.13.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/fire.mp3
    - assets/animations/fire.json

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png" 
